// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    ABreadcrumb: typeof import('@arco-design/web-vue')['Breadcrumb']
    ABreadcrumbItem: typeof import('@arco-design/web-vue')['BreadcrumbItem']
    ACard: typeof import('@arco-design/web-vue')['Card']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    APageHeader: typeof import('@arco-design/web-vue')['PageHeader']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    ASkeleton: typeof import('@arco-design/web-vue')['Skeleton']
    ASkeletonShape: typeof import('@arco-design/web-vue')['SkeletonShape']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    ExternalLink: typeof import('./src/components/ExternalLink.vue')['default']
    Footer: typeof import('./src/layout/Footer.vue')['default']
    Header: typeof import('./src/layout/Header.vue')['default']
    IconFile: typeof import('@arco-design/web-vue/es/icon')['IconFile']
    IconGithub: typeof import('@arco-design/web-vue/es/icon')['IconGithub']
    IconHome: typeof import('@arco-design/web-vue/es/icon')['IconHome']
    IconLeft: typeof import('@arco-design/web-vue/es/icon')['IconLeft']
    IconUser: typeof import('@arco-design/web-vue/es/icon')['IconUser']
    Markdown: typeof import('./src/components/Markdown.vue')['default']
    PageError: typeof import('./src/layout/PageError.vue')['default']
    PageHome: typeof import('./src/layout/PageHome.vue')['default']
    PagePlainText: typeof import('./src/layout/PagePlainText.vue')['default']
  }
}
