// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    Footer: typeof import('./src/layout/Footer.vue')['default']
    Header: typeof import('./src/layout/Header.vue')['default']
    Markdown: typeof import('./src/components/Markdown.vue')['default']
    PageError: typeof import('./src/layout/PageError.vue')['default']
    PageHome: typeof import('./src/layout/PageHome.vue')['default']
    PagePlainText: typeof import('./src/layout/PagePlainText.vue')['default']
  }
}
